networks:
  api-db:
    driver: bridge

services:
  diplomwork.webapi:
    image: ${DOCKER_REGISTRY-}diplomworkwebapi
    build:
      context: .
      dockerfile: DiplomWork.WebApi/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - api-db
    depends_on:
      - postgres

  postgres:
     container_name: postgres2
     image: postgres:latest
     environment:
       POSTGRES_DB: "diplom_db"
       POSTGRES_USER: "admin"
       POSTGRES_PASSWORD: "PmcMBwX3bNvGzv5"
     networks:
       - api-db
     volumes:
       - postgres-data:/var/lib/postgresql/data
     ports:
       - "5432:5432"
  
  front:
    image: ${DOCKER_REGISTRY-}diplomworkfront
    build:
      context: ../DiplomWorkFront
      dockerfile: Dockerfile
    ports:
      - "4173:4173"

volumes:
  postgres-data:
